[package]
name = "romexp2"
version = "0.1.0"
authors = ["Adam Mayer <phooky@gmail.com>"]

[dependencies]
clap = "2.26.0"
memmap = "0.5.2"
glium = "0.17.0"
imgui = "0.0.15"
imgui-glium-renderer = "0.0.15"
